# Generated by Django 4.0.2 on 2022-04-22 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_percent', models.BooleanField(default=True)),
                ('offer_amount', models.PositiveBigIntegerField()),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('postal_code', models.CharField(help_text='Maximum length for postal code is 10 character.', max_length=10)),
                ('authority', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('pay_amount', models.PositiveIntegerField()),
                ('payment_id', models.CharField(blank=True, max_length=18, null=True)),
                ('status', models.CharField(choices=[('1', 'اقدام به پرداخت'), ('2', 'اتمام پرداخت'), ('3', 'دریافت از انبار'), ('4', 'در حال چاپ'), ('5', 'آماده\u200cی ارسال'), ('6', 'تحویل داده شده به شرکت پست'), ('7', 'دریافت شده توسط مشتری')], default='1', max_length=1)),
                ('is_paid_to_provider', models.BooleanField(default=False)),
                ('offer_key', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
