# Generated by Django 4.0.2 on 2022-04-27 13:16

from django.db import migrations


def make_many_products(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Order = apps.get_model('orders', 'Order')

    for order in Order.objects.all():
        order.products.add(order.product)


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_order_products_alter_order_product'),
    ]

    operations = [
        migrations.RunPython(make_many_products),
    ]
