# Generated by Django 4.0.2 on 2022-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_amount',
            field=models.PositiveIntegerField(default=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'اقدام به پرداخت'), ('2', 'اتمام پرداخت'), ('3', 'دریافت از انبار'), ('4', 'در حال چاپ'), ('5', 'آماده\u200cی ارسال'), ('6', 'تحویل داده شده به شرکت پست'), ('7', 'دریافت شده توسط مشتری')], default='1', max_length=1),
        ),
    ]
