# Generated by Django 4.0.2 on 2022-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_price_amount_coupon_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
