# Generated by Django 3.2.13 on 2022-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_sum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Maximum length for postal code is 10 character.', max_length=10, null=True),
        ),
    ]
