# Generated by Django 4.0.2 on 2022-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon_expire_date_alter_coupon_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
