# Generated by Django 4.0.2 on 2022-04-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_coupon_offer_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='description',
            new_name='descr',
        ),
    ]
