# Generated by Django 4.0.2 on 2022-04-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_description_coupon_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='descr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pay_amount',
            new_name='pay_amoun',
        ),
    ]
