# Generated by Django 3.2.13 on 2022-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_sum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
