# Generated by Django 4.0.2 on 2022-04-22 15:33

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pro_code', models.PositiveSmallIntegerField(unique=True)),
                ('image', models.ImageField(upload_to=products.models.product_image_path)),
                ('instagram_url', models.URLField()),
                ('channel_message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sell_price', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
