# Generated by Django 4.0.2 on 2022-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='channel_message_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
