# Generated by Django 4.0.2 on 2022-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_channel_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='channel_message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
